import {
  Zap, Users, Heart, Sparkles, Baby, UserCheck,
  HeartHandshake, Armchair, Music, HandMetal, Shield,
  BookOpen, GraduationCap, Globe, Monitor, Flame,
} from 'lucide-react';

export const NATURAL_GROUP_DEFINITIONS = [
  {
    type: 'yaya',
    name: 'YAYA — Young Adults & Youth Assembly',
    shortName: 'YAYA',
    slug: 'yaya',
    icon: Zap,
    description: 'Raising a generation of young believers who are rooted in the Word, relevant in society, and ready for the Master\'s use.',
    defaultMeetingDay: 'Friday',
    defaultMeetingTime: '5:30 PM',
  },
  {
    type: 'men-fellowship',
    name: 'Men Fellowship',
    shortName: 'Men Fellowship',
    slug: 'men-fellowship',
    icon: Users,
    description: 'A fellowship of men committed to spiritual growth, family leadership, and community impact through Christ.',
    defaultMeetingDay: 'Saturday',
    defaultMeetingTime: '8:00 AM',
  },
  {
    type: 'women-fellowship',
    name: 'Good Women Fellowship',
    shortName: 'Women Fellowship',
    slug: 'women-fellowship',
    icon: Heart,
    description: 'Women united in faith, prayer, and service, building godly homes and impacting communities.',
    defaultMeetingDay: 'Saturday',
    defaultMeetingTime: '9:00 AM',
  },
  {
    type: 'teens-church',
    name: 'Teens Church',
    shortName: 'Teens Church',
    slug: 'teens-church',
    icon: Sparkles,
    description: 'Nurturing teenagers in the faith with age-appropriate teachings, mentorship, and fellowship.',
    defaultMeetingDay: 'Sunday',
    defaultMeetingTime: '9:00 AM',
  },
  {
    type: 'children-church',
    name: 'Children Church',
    shortName: 'Children Church',
    slug: 'children-church',
    icon: Baby,
    description: 'Teaching children the Word of God through creative storytelling, worship, and interactive lessons.',
    defaultMeetingDay: 'Sunday',
    defaultMeetingTime: '9:00 AM',
  },
  {
    type: 'singles-fellowship',
    name: 'Singles Fellowship',
    shortName: 'Singles Fellowship',
    slug: 'singles-fellowship',
    icon: UserCheck,
    description: 'A community for single believers to grow spiritually, build friendships, and prepare for God\'s purpose.',
    defaultMeetingDay: 'Saturday',
    defaultMeetingTime: '4:00 PM',
  },
  {
    type: 'married-couples',
    name: 'Married Couples Fellowship',
    shortName: 'Married Couples',
    slug: 'married-couples',
    icon: HeartHandshake,
    description: 'Strengthening marriages through biblical teachings, counseling, and shared fellowship.',
    defaultMeetingDay: 'Saturday',
    defaultMeetingTime: '5:00 PM',
  },
  {
    type: 'senior-citizens',
    name: 'Senior Citizens Fellowship',
    shortName: 'Senior Citizens',
    slug: 'senior-citizens',
    icon: Armchair,
    description: 'Honoring our elders with fellowship, care, and continued spiritual engagement.',
    defaultMeetingDay: 'Wednesday',
    defaultMeetingTime: '10:00 AM',
  },
  {
    type: 'choir',
    name: 'Choir Ministry',
    shortName: 'Choir',
    slug: 'choir',
    icon: Music,
    description: 'Leading the congregation in worship through anointed songs and musical excellence.',
    defaultMeetingDay: 'Saturday',
    defaultMeetingTime: '4:00 PM',
  },
  {
    type: 'ushers',
    name: 'Ushers Unit',
    shortName: 'Ushers',
    slug: 'ushers',
    icon: HandMetal,
    description: 'Welcoming and guiding worshippers with warmth, ensuring orderly and joyful services.',
    defaultMeetingDay: 'Saturday',
    defaultMeetingTime: '5:00 PM',
  },
  {
    type: 'protocol',
    name: 'Protocol Unit',
    shortName: 'Protocol',
    slug: 'protocol',
    icon: Shield,
    description: 'Ensuring smooth coordination of church events, VIP management, and organizational flow.',
    defaultMeetingDay: 'Saturday',
    defaultMeetingTime: '3:00 PM',
  },
  {
    type: 'sunday-school',
    name: 'Sunday School',
    shortName: 'Sunday School',
    slug: 'sunday-school',
    icon: BookOpen,
    description: 'Deepening biblical knowledge and understanding through structured weekly study.',
    defaultMeetingDay: 'Sunday',
    defaultMeetingTime: '8:30 AM',
  },
  {
    type: 'workers-in-training',
    name: 'Workers-in-Training (WIT)',
    shortName: 'WIT',
    slug: 'workers-in-training',
    icon: GraduationCap,
    description: 'Training and equipping new workers for effective service in the house of God.',
    defaultMeetingDay: 'Saturday',
    defaultMeetingTime: '10:00 AM',
  },
  {
    type: 'evangelism',
    name: 'Evangelism Ministry',
    shortName: 'Evangelism',
    slug: 'evangelism',
    icon: Globe,
    description: 'Reaching the lost with the gospel through outreach, street evangelism, and community missions.',
    defaultMeetingDay: 'Saturday',
    defaultMeetingTime: '7:00 AM',
  },
  {
    type: 'media-technical',
    name: 'Media & Technical Ministry',
    shortName: 'Media & Tech',
    slug: 'media-technical',
    icon: Monitor,
    description: 'Handling sound, lighting, projections, live streaming, and digital communications.',
    defaultMeetingDay: 'Saturday',
    defaultMeetingTime: '3:00 PM',
  },
  {
    type: 'prayer-intercession',
    name: 'Prayer & Intercession Unit',
    shortName: 'Prayer Unit',
    slug: 'prayer-intercession',
    icon: Flame,
    description: 'Standing in the gap through fervent prayers, intercession, and spiritual warfare.',
    defaultMeetingDay: 'Wednesday',
    defaultMeetingTime: '6:00 PM',
  },
] as const;

export type NaturalGroupDefinition = typeof NATURAL_GROUP_DEFINITIONS[number];
